sudo: required
language: generic
services:
  - docker


before_install:
  - docker build -t Sujay/docker-react-app -f Dockerfile.dev .

script:
  - docker run Sujay/docker-react-app npm run test -- --coverage
